# Generated by Django 6.0.2 on 2026-03-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
