# Generated by Django 6.0.2 on 2026-03-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expenses_date_alter_expenses_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
